version: '3.0'

services:
    php:
        build:
            context: ./docker/php
        image: camunda-symfony-example-php
        volumes:
            - ./app:/opt/app
            - ./docker/php/zz-log.conf:/usr/local/etc/php/conf.d/zz-log.conf
    db:
        image: postgres:12
        volumes:
            - ./var/postgres-data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: camunda
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: camunda
    camunda:
        image: camunda/camunda-bpm-platform:7.18.0
        depends_on:
            - db
        hostname: camunda
        ports:
            - "8080:8080"
        restart: always
        environment:
            DB_DRIVER: org.postgresql.Driver
            DB_URL: jdbc:postgresql://db:5432/camunda
            DB_USERNAME: camunda
            DB_PASSWORD: secret
            WAIT_FOR: db:5432
    worker:
        command: /opt/app/bin/console -vv messenger:consume camunda
        deploy:
            replicas: 2
        image: camunda-symfony-example-php
        depends_on:
            - camunda
        volumes:
            - ./app:/opt/app
            - ./docker/php/zz-log.conf:/usr/local/etc/php/conf.d/zz-log.conf
